### ISSUE TITLE
Any plans to support Renoir (4000 series devices)

### ISSUE THREAD

**Issue by gadgethm** [conqp/amd-sfh-hid-dkms#2]
I have an HP Envy x360 with a 4700U CPU in it.  This driver allows my computer to see the rotation sensor:
```
$ monitor-sensor
    Waiting for iio-sensor-proxy to appear
+++ iio-sensor-proxy appeared
=== Has accelerometer (orientation: undefined)
=== No ambient light sensor
=== No proximity sensor
```
But rotating the laptop does not produce any results.  Is this a limitation which having hardware could help resolve?  I am happy to provide hardware details and do some digging if it will help push this forward.

**Comment by gadgethm** [comment]
Ahh my mistake, it looks like this is an upstream issue with the AMD driver.  Closing.

**Comment by RobinJ1995** [comment]
@gadgethm Would you have a link to that upstream ticket? I have the same laptop, and the same issue.

**Comment by conqp** [comment]
https://bugzilla.kernel.org/show_bug.cgi?id=199715
https://www.phoronix.com/scan.php?page=news_item&px=AMD-SFH-Next-Gen-Patches
